# Generated by Django 5.2.8 on 2025-11-27 02:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Psw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('password', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)])),
            ],
        ),
    ]
