# Generated by Django 5.2.8 on 2025-11-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_psw'),
    ]

    operations = [
        migrations.AddField(
            model_name='psw',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
