# Generated by Django 5.2.8 on 2025-11-28 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_psw_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField()),
                ('delicious', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.delicious')),
            ],
        ),
    ]
